### ISSUE TITLE
Dropped message

### ISSUE THREAD

**Issue by zzkt** [ether/ep_git_commit_saved_revision#1]
I've installed & configured the plugin but after the commit message window appears I get a warning 

`Dropped message, unknown COLLABROOM Data  Type gitcommit` 

Is there anything else that needs to be setup (or tested)?

**Comment by JohnMcLear** [comment]
@zzkt will test this AM and let you know :)

**Comment by JohnMcLear** [comment]
Okay installed with git clone then did npm install in the plugin folder.

My settings.json is

```
  "ep_git_commit_saved_revision":{
    "path":"/home/jose/develop/var/git",
    "initCommand":"git init ${path}",
    "saveCommand":"git -C \"${path}\" add \"${padId}.txt\" && git -C \"${path}\" commit -m \"${message}\""
  }
```

**Comment by JohnMcLear** [comment]
I clicked save revision, put in a msg, hit save or whatever

In console on server I get

```

[2020-05-14 10:12:58.772] [INFO] ueberDB - Flushed 2 values
[2020-05-14 10:13:01.474] [WARN] console - message {
  type: 'gitcommit',
  action: 'sendgitcommitMessage',
  message: 'derp',
  padId: 'kzLTe9xDuuwR5eSKTxm9',
  myAuthorId: 'a.wO8h57aAvrfm9X4M'
}
[2020-05-14 10:13:01.487] [INFO] ueberDB - Flushed 1 values
```

No errors etc.

**Comment by JohnMcLear** [comment]
Did you restart Etherpad after installing?  I assume so.

Running latest ``Develop`` branch of Etherpad or 1.8+?

**Comment by JohnMcLear** [comment]
```
commit 5bc36fcde625617841c5369d77af313ec4296f52 (HEAD -> master)
Author: John McLear <john@mclear.co.uk>
Date:   Thu May 14 10:13:02 2020 +0000

    derp
```

Seems to be working fine.. ??

**Comment by zzkt** [comment]
I'm running 1.8.3 (haven't tested with the develop branch) and have a similar config as above. I've tried restarting with both run & fastrun, but no luck.

**Comment by JohnMcLear** [comment]
``Dropped message, unknown COLLABROOM Data Type gitcommit`` suggests that the msg is being sent from browser > Server but the servers handleMessage hook isn't being properly handled.

Do you have any other plugins enabled/installed?

**Comment by zzkt** [comment]
It's working as expected now (with other plugins). I think it was a problem with using an existing git repo, when i changed `path` to a new folder it was fine.

**Comment by zzkt** [comment]
Thanks for the help.  Is there a way to commit the changes with out the pop-up message window appearing? 
(e.g. using something like `git -C \"${path}\" commit -m \"${padId} ${myAuthorId}\""`)

**Comment by JohnMcLear** [comment]
Yea, just comment the pop up code out and make it submit it or something :P  I could add it as an option but it should be easy enough if you are even slightly familiar with programming to submit this feature request as a pull request?
